version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo/accia
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
